name: catequese_app
description: "Projeto de ficha de catequese para a paróquia de São José Operário"
publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: '>=3.1.0 <4.0.0' # Ajustado para compatibilidade geral

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  signature: 6.3.0
  drift: 2.32.0
  sqlite3_flutter_libs: 0.6.0+eol
  path_provider: 2.1.5
  path: 1.9.1
  uuid: 4.5.3
  printing: 5.14.3
  pdf: 3.12.0
  mask_text_input_formatter: 2.9.0
  http: 1.6.0
  shared_preferences: 2.5.4
  google_sign_in: 7.2.0
  file_picker: 11.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  drift_dev: 2.32.0
  build_runner: 2.13.0
  # Adicionado para gerar os ícones:
  flutter_launcher_icons: 0.13.1

# Configuração dos ícones para todas as plataformas
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/icon.png"
  windows:
    generate: true
    image_path: "assets/icon.png"
  macos:
    generate: true
    image_path: "assets/icon.png"
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/icon.png # Adicionado aqui também